### ISSUE TITLE
Whitespace/listcharts don't respect background color

### ISSUE THREAD

**Issue by fedemp** [cormacrelf/vim-colors-github#1]
Nice colorscheme but tabs and whitespace are using a darker background (using soft colors).

![1539695699](https://user-images.githubusercontent.com/735314/47018992-6949a380-d12c-11e8-903e-d70fa593b08b.png)

**Comment by cormacrelf** [comment]
Note to self: handle NonText and SpecialKey hi groups 

Edit: nope. Whitespace
