### ISSUE TITLE
Clear permission statement related to GitHub Terms of Service

### ISSUE THREAD

**Issue by 3719e04** [cormacrelf/vim-colors-github#14]
Hi,

I was reading https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-terms-of-service#g-intellectual-property-notice, and noticed

> You may not duplicate, copy, or reuse any portion of the HTML/CSS, Javascript, or visual design elements or concepts without express written permission from GitHub.

Maybe it'll be better to put the written permission from GitHub in your project README, so users are clear about licensing.

**Comment by cormacrelf** [comment]
Please consider for yourself whether your use of these colours violates your own TOS with GitHub. For example, I don't think it would be wise to start a professional screencast series using this colorscheme, and this is unaffected by whether the theme itself was created with permission. I (just a guy) cannot, and do not claim to, offer you a license to use a large corporation's intellectual property, and I don't imagine they're about to draft any sort of license to it either. You're right, this is probably a good thing to note.

**Comment by 3719e04** [comment]
Thank you! Now I realize I misread the GitHub ToS. Closing.

**Comment by cormacrelf** [comment]
You didn't misread it.
