### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by luisdavim** [cormacrelf/vim-colors-github#3]
Hi, I use the Dark Reader browser plugin https://darkreader.org/ and Github looks great in dark, I'd love to have that look in vim.

**Comment by cormacrelf** [comment]
Go make it! The colours for this are defined at the top of the file, so you can use your browser devtools to find what colours text ends up with dark styles applied, and update the corresponding colour values. Then tweak the greys.

**Comment by cormacrelf** [comment]
![Screen Shot 2019-08-30 at 18 05 10](https://user-images.githubusercontent.com/378760/64004008-d1408700-cb50-11e9-83d2-da006706efb1.png)

A little sneak preview of what I'm working on.

**Comment by imjasonmiller** [comment]
Hi @cormacrelf, are you still working on the above? I came across the official [Visual Studio code theme](https://github.com/primer/github-vscode-theme) from Github's Primer design system and it also features a dark mode.

I thought about creating it myself at first, but found this repository and, seeing the great amount of work you've already put in, thought it might be better to ask if you're open to contributions than start anew.

I installed Visual Studio Code and the Github Dark theme to give you an idea of what the code samples in the current `README` would look like:

![image](https://user-images.githubusercontent.com/12190184/81494685-1b1a6900-92ab-11ea-8730-07b195dcaed3.png)

Or the code sample above:

![image](https://user-images.githubusercontent.com/12190184/81494345-7ac34500-92a8-11ea-8ab5-8b6858cf7b8d.png)

It does look like some of the tokens in Visual Studio Code don't have styles applied to them yet, e.g. inner and outer attributes in Rust.

**Comment by imjasonmiller** [comment]
@cormacrelf @alesshh [I just started work on a dark mode](https://github.com/imjasonmiller/vim-colors-github/tree/feature_dark_mode) and I'd love to hear your thoughts.

Do you want me to maintain compatibility with the `github` theme? As of right now, for easier development, I split the theme into `colors/github.vim` and `colors/githubdark.vim`, as the`lightline` color scheme calls `ghGreen`, `ghRed` and others, which slightly differ in the `githubdark` theme. I think that unfortunately means one can't have the dark theme for `lightline` while using the light color scheme and vice versa. If that's an issue, I could perhaps namespace the colors and hide the color scheme option behind  a flag in `colors/github.vim` if you'd prefer that?

It can of course always live on as a separate fork if you're fine with the theme as is :-) 

![image](https://user-images.githubusercontent.com/12190184/82691194-cfc66a00-9c5d-11ea-9f1e-07acc1d0cec9.png)
![image](https://user-images.githubusercontent.com/12190184/82691405-2469e500-9c5e-11ea-9041-c98a4be1a760.png)

I'm slowly adding colors to it though. I just added them for `lightline`. 

![image](https://user-images.githubusercontent.com/12190184/82692947-e0c4aa80-9c60-11ea-8b85-05fdd816846a.png)

I extracted and grouped all the colors from the Visual Studio Code theme, but I've opted for some lighter and darker tones where appropriate.

![image](https://user-images.githubusercontent.com/12190184/82695623-ba553e00-9c65-11ea-918b-c7beb44e78c7.png)

![image](https://user-images.githubusercontent.com/12190184/82695669-d22cc200-9c65-11ea-8b1a-cbcb42b4c5a8.png)

**Comment by cormacrelf** [comment]
Hey guys, sorry I missed all this discussion. @imjasonmiller yours looks great! See the new PR for my take.

It is the product of tweaking it bit by bit for a very long time. I'm probably going to merge my own, since:

- I wrote it (I'm biased, I know) and have been using it
- It's best to keep it in one file for `set bg=dark` compatibility
- The dark and the light feel like one and the same theme, whereas yours feels like a different one. It's equally good, but it's got that more vibrant look. Give it a new name and they can coexist, I think, as perhaps the two best dark vim themes.

All in all, try it out, see what you think.

**Comment by imjasonmiller** [comment]
Hey @cormacrelf, not an issue at all! Great to hear from you, hope you're doing well. I'll definitely give it a try and look into the latter when I have the time.

Have a great day!
