### ISSUE TITLE
SignColumn doesn't render like LineNr

### ISSUE THREAD

**Issue by idanko-sv** [cormacrelf/vim-colors-github#4]
## Summary
SignColum part is not rendering properly when the `let g:ale_sign_column_always = 1` sets. I couldn't confirm the issue reproducible in another setup.

## Reproduced on
* Vimr: NVIM 0.3.4
* Macvim: VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 18 2019 23:51:40)
macOS version
Included patches: 1-950

## Expected behavior
* SignColum has the same color scheme as LineNr

## Actual
* SignColum sets to grey

<img width="735" alt="Screen Shot 2019-04-12 at 12 37 38 PM" src="https://user-images.githubusercontent.com/46958452/56028004-d5921200-5d1f-11e9-9085-56ebd35723e7.png">

**Comment by cormacrelf** [comment]
Sounds like... a problem with ale?

**Comment by idanko-sv** [comment]
@cormacrelf I've changed appropriate lines to:
```
call s:Col('SignColumn',       'base4',  'gutter')
call s:Col('EndOfBuffer',       'base4',  'gutter')
```
and the issue gone, but it sounds like controversial approach, and don't wanna PR

**Comment by idanko-sv** [comment]
@cormacrelf hi, confirm that the issue is reproduced on other themes, however on some of them such as gruvbox, user experience is nicer since SignColumn background has pretty the same color pallet as Normal.
