### ISSUE TITLE
Does not recognize `.exs` as valid file format

### ISSUE THREAD

**Issue by pdgonzalez872** [cormacrelf/vim-colors-github#7]
Hi! I love the theme!

I use Elixir and the `.ex` files work great. But it seems like the `.exs` (the test files) don't get recognized.

I'm not sure if this is a config here, or somewhere else in my `vimrc`. If not a problem here, could you please point me to another place to look? Thanks!

**Comment by cormacrelf** [comment]
Not here. You installed the elixir syntax all by yourself, you tell me where it lives.

**Comment by pdgonzalez872** [comment]
Perfect, thanks!
